/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MetodosRouteImport } from './routes/metodos'
import { Route as ProgressoRouteImport } from './routes/progresso'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as PuzzlesPuzzleIdIndexRouteImport } from './routes/puzzles.$puzzleId.index'
import { Route as PuzzlesPuzzleIdMethodIdIndexRouteImport } from './routes/puzzles.$puzzleId.$methodId.index'
import { Route as PuzzlesPuzzleIdMethodIdCaseIdRouteImport } from './routes/puzzles.$puzzleId.$methodId.$caseId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MetodosRoute = MetodosRouteImport.update({
  id: '/metodos',
  path: '/metodos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProgressoRoute = ProgressoRouteImport.update({
  id: '/progresso',
  path: '/progresso',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesPuzzleIdIndexRoute = PuzzlesPuzzleIdIndexRouteImport.update({
  id: '/puzzles/$puzzleId/',
  path: '/puzzles/$puzzleId/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesPuzzleIdMethodIdIndexRoute =
  PuzzlesPuzzleIdMethodIdIndexRouteImport.update({
    id: '/puzzles/$puzzleId/$methodId/',
    path: '/puzzles/$puzzleId/$methodId/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PuzzlesPuzzleIdMethodIdCaseIdRoute =
  PuzzlesPuzzleIdMethodIdCaseIdRouteImport.update({
    id: '/puzzles/$puzzleId/$methodId/$caseId',
    path: '/puzzles/$puzzleId/$methodId/$caseId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/metodos': typeof MetodosRoute
  '/progresso': typeof ProgressoRoute
  '/sobre': typeof SobreRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId/': typeof PuzzlesPuzzleIdIndexRoute
  '/puzzles/$puzzleId/$methodId/$caseId': typeof PuzzlesPuzzleIdMethodIdCaseIdRoute
  '/puzzles/$puzzleId/$methodId/': typeof PuzzlesPuzzleIdMethodIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/metodos': typeof MetodosRoute
  '/progresso': typeof ProgressoRoute
  '/sobre': typeof SobreRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdIndexRoute
  '/puzzles/$puzzleId/$methodId/$caseId': typeof PuzzlesPuzzleIdMethodIdCaseIdRoute
  '/puzzles/$puzzleId/$methodId': typeof PuzzlesPuzzleIdMethodIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/metodos': typeof MetodosRoute
  '/progresso': typeof ProgressoRoute
  '/sobre': typeof SobreRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId/': typeof PuzzlesPuzzleIdIndexRoute
  '/puzzles/$puzzleId/$methodId/$caseId': typeof PuzzlesPuzzleIdMethodIdCaseIdRoute
  '/puzzles/$puzzleId/$methodId/': typeof PuzzlesPuzzleIdMethodIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/metodos'
    | '/progresso'
    | '/sobre'
    | '/puzzles/'
    | '/puzzles/$puzzleId/'
    | '/puzzles/$puzzleId/$methodId/$caseId'
    | '/puzzles/$puzzleId/$methodId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/metodos'
    | '/progresso'
    | '/sobre'
    | '/puzzles'
    | '/puzzles/$puzzleId'
    | '/puzzles/$puzzleId/$methodId/$caseId'
    | '/puzzles/$puzzleId/$methodId'
  id:
    | '__root__'
    | '/'
    | '/metodos'
    | '/progresso'
    | '/sobre'
    | '/puzzles/'
    | '/puzzles/$puzzleId/'
    | '/puzzles/$puzzleId/$methodId/$caseId'
    | '/puzzles/$puzzleId/$methodId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MetodosRoute: typeof MetodosRoute
  ProgressoRoute: typeof ProgressoRoute
  SobreRoute: typeof SobreRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  PuzzlesPuzzleIdIndexRoute: typeof PuzzlesPuzzleIdIndexRoute
  PuzzlesPuzzleIdMethodIdCaseIdRoute: typeof PuzzlesPuzzleIdMethodIdCaseIdRoute
  PuzzlesPuzzleIdMethodIdIndexRoute: typeof PuzzlesPuzzleIdMethodIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/metodos': {
      id: '/metodos'
      path: '/metodos'
      fullPath: '/metodos'
      preLoaderRoute: typeof MetodosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/progresso': {
      id: '/progresso'
      path: '/progresso'
      fullPath: '/progresso'
      preLoaderRoute: typeof ProgressoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$puzzleId/': {
      id: '/puzzles/$puzzleId/'
      path: '/puzzles/$puzzleId'
      fullPath: '/puzzles/$puzzleId/'
      preLoaderRoute: typeof PuzzlesPuzzleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$puzzleId/$methodId/': {
      id: '/puzzles/$puzzleId/$methodId/'
      path: '/puzzles/$puzzleId/$methodId'
      fullPath: '/puzzles/$puzzleId/$methodId/'
      preLoaderRoute: typeof PuzzlesPuzzleIdMethodIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$puzzleId/$methodId/$caseId': {
      id: '/puzzles/$puzzleId/$methodId/$caseId'
      path: '/puzzles/$puzzleId/$methodId/$caseId'
      fullPath: '/puzzles/$puzzleId/$methodId/$caseId'
      preLoaderRoute: typeof PuzzlesPuzzleIdMethodIdCaseIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MetodosRoute: MetodosRoute,
  ProgressoRoute: ProgressoRoute,
  SobreRoute: SobreRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  PuzzlesPuzzleIdIndexRoute: PuzzlesPuzzleIdIndexRoute,
  PuzzlesPuzzleIdMethodIdCaseIdRoute: PuzzlesPuzzleIdMethodIdCaseIdRoute,
  PuzzlesPuzzleIdMethodIdIndexRoute: PuzzlesPuzzleIdMethodIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
