/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PuzzlesIndexRouteImport } from './routes/puzzles.index'
import { Route as PuzzlesPuzzleIdIndexRouteImport } from './routes/puzzles.$puzzleId.index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesIndexRoute = PuzzlesIndexRouteImport.update({
  id: '/puzzles/',
  path: '/puzzles/',
  getParentRoute: () => rootRouteImport,
} as any)
const PuzzlesPuzzleIdIndexRoute = PuzzlesPuzzleIdIndexRouteImport.update({
  id: '/puzzles/$puzzleId/',
  path: '/puzzles/$puzzleId/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId/': typeof PuzzlesPuzzleIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/puzzles': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId': typeof PuzzlesPuzzleIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/puzzles/': typeof PuzzlesIndexRoute
  '/puzzles/$puzzleId/': typeof PuzzlesPuzzleIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/puzzles/' | '/puzzles/$puzzleId/'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/puzzles' | '/puzzles/$puzzleId'
  id: '__root__' | '/' | '/puzzles/' | '/puzzles/$puzzleId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  PuzzlesIndexRoute: typeof PuzzlesIndexRoute
  PuzzlesPuzzleIdIndexRoute: typeof PuzzlesPuzzleIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/': {
      id: '/puzzles/'
      path: '/puzzles'
      fullPath: '/puzzles/'
      preLoaderRoute: typeof PuzzlesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/puzzles/$puzzleId/': {
      id: '/puzzles/$puzzleId/'
      path: '/puzzles/$puzzleId'
      fullPath: '/puzzles/$puzzleId/'
      preLoaderRoute: typeof PuzzlesPuzzleIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  PuzzlesIndexRoute: PuzzlesIndexRoute,
  PuzzlesPuzzleIdIndexRoute: PuzzlesPuzzleIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
